export { IconDashboard } from './IconDashboard'
export { IconReceipt } from './IconReceipt'
export { IconVAT } from './IconVAT'
export { IconSettings } from './IconSettings'
export { IconUpload } from './IconUpload'
export { IconSignOut } from './IconSignOut'
export { Logomark } from './Logomark'
export { C } from '../../../styles/colours'
